### ISSUE TITLE
не работает кнопка загрузить параметры

### ISSUE THREAD

**Issue by qasef** [evgenylavelin/consquery#21]
бух 3.0 8.3.10
{ВнешняяОбработка.КонсольЗапросов.Форма.ФормаУпр.Форма(1445)}: Ошибка при вызове метода контекста (ПолучитьПараметрыЗапросаНаСервере)
	лПараметры = ПолучитьПараметрыЗапросаНаСервере(ТекстЗапроса, ТекстОшибки);
по причине:
Ошибка передачи данных между клиентом и сервером. Значение недопустимого типа.
по причине:
Ошибка преобразования данных XDTO:
Запись значения свойства 'ret':
	форма: Элемент
	имя: {http://v8.1c.ru/8.2/managed-application/modules}ret
по причине:
Ошибка отображения типов:
Отсутствует отображение для типа 'ОписаниеПараметровЗапроса'

**Comment by evgenylavelin** [comment]
Можно пример запроса, в котором воспроизводится ошибка?

**Comment by qasef** [comment]
да любой, например выбрать * из Справочник.контрагенты где ссылка = &ссылка

**Comment by evgenylavelin** [comment]
В 3.1.4-b23 исправлена данная ошибка
