### ISSUE TITLE
не открывается ранее сохранённый файл запросов

### ISSUE THREAD

**Issue by qasef** [evgenylavelin/consquery#22]
бух 3.0 8.3.10

[111.zip](https://github.com/evgenylavelin/consquery/files/1766133/111.zip)
{ВнешняяОбработка.КонсольЗапросов.Форма.ФормаУпр.Форма(1674)}: Значение не является значением объектного типа (ТекстЗапроса)
		ТекстЗапросаТекущаяСтрока = лСтрокаСЗапросом.ТекстЗапроса;

**Comment by evgenylavelin** [comment]
в релизе 3.1.4-b23 загружается
