### ISSUE TITLE
при закрытии 1с с открытой консолью запросов ошибка

### ISSUE THREAD

**Issue by qasef** [evgenylavelin/consquery#23]
бух 3.0
8.3.10

{ВнешняяОбработка.КонсольЗапросов.Форма.ФормаУпр.Форма(395)}: Ошибка при вызове метода контекста (ПоказатьВопрос)
		ПоказатьВопрос(Новый ОписаниеОповещения("ПередЗакрытиемЗавершение", Вычислить(ЭтотОбъектФорма), Модифицированность), ТекстВопроса, КнопкиВопроса);
по причине:
Открытие окон при завершении работы запрещено

**Comment by evgenylavelin** [comment]
Эта ошибка зарегистрирована уже [здесь](https://github.com/evgenylavelin/consquery/issues/19).
Тут дилема: либо исключить поддержку "старых" релизов, либо "терпеть" ругань платформы.
