### ISSUE TITLE
Конструктор не найден ПоказатьВводСтроки, 

### ISSUE THREAD

**Issue by qasef** [evgenylavelin/consquery#26]
Ошибка инициализации модуля: ВнешняяОбработка.КонсольЗапросов.Форма.ФормаУпр.Форма
по причине:
{ВнешняяОбработка.КонсольЗапросов.Форма.ФормаУпр.Форма(575,28)}: Конструктор не найден
		ПоказатьВводСтроки(Новый <<?>>ОписаниеОповещения, гСтроковоеПредставлениеТипа(ТипОбработка, СеансовыеДанные, ТипЗнч(СодержимоеЯчейки)), "Тип значения", ,Истина);

бухгалтерия 3.0, 8.3.9

**Comment by qasef** [comment]
консоль с гитхаба текущая

**Comment by evgenylavelin** [comment]
В 8.3.9, видимо, недопустимо использовать пустой конструктор Новый ОписаниеОповещения. 
Добавил в 3.1.4-b24 пустой обработчик оповещения для совместимости.
