### ISSUE TITLE
{ВнешняяОбработка.КонсольЗапросов.Форма.ФормаУпр.Форма(1457)}: Индекс находится за границами массива

### ISSUE THREAD

**Issue by qasef** [evgenylavelin/consquery#27]
при нажатии на кнопку "загрузить параметры из запроса"
{ВнешняяОбработка.КонсольЗапросов.Форма.ФормаУпр.Форма(1457)}: Индекс находится за границами массива
		лРезультат.Добавить(Новый Структура("Имя, ТипЗначения, ИмяXML", лПараметр.Имя, лПараметр.ТипЗначения, XMLТип(лПараметр.ТипЗначения.Типы()[0]).ИмяТипа));

8.3.10 упр формы. бухгалтерия 3.0
запрос такой

ВЫБРАТЬ
	ХозрасчетныйОбороты.Организация КАК Организация,
	ЕСТЬNULL(ХозрасчетныйОбороты.Субконто3, ЗНАЧЕНИЕ(Справочник.РегистрацииВНалоговомОргане.ПустаяСсылка)) КАК РегистрацияВНалоговомОргане,
	ХозрасчетныйОбороты.Субконто2 КАК Бюджет,
	СУММА(ХозрасчетныйОбороты.СуммаОборотКт) КАК СуммаНалогГод,
	СУММА(ВЫБОР
			КОГДА ХозрасчетныйОбороты.Период = &НачалоМесяца
				ТОГДА ХозрасчетныйОбороты.СуммаОборотКт
			ИНАЧЕ 0
		КОНЕЦ) КАК СуммаНалогМесяц
ПОМЕСТИТЬ НалогПоПериодам
ИЗ
	РегистрБухгалтерии.Хозрасчетный.Обороты(
			&НачалоПериода,
			&КонецПериода,
			Месяц,
			Счет В (&СчетаРасчетыСБюджетом),
			&Субконто68_04_1,
			Организация В (&СписокОрганизаций)
				И Субконто1 = ЗНАЧЕНИЕ(Перечисление.ВидыПлатежейВГосБюджет.Налог)
				И Субконто2 В (ЗНАЧЕНИЕ(Перечисление.УровниБюджетов.ФедеральныйБюджет), ЗНАЧЕНИЕ(Перечисление.УровниБюджетов.РегиональныйБюджет)),
			,
			) КАК ХозрасчетныйОбороты

СГРУППИРОВАТЬ ПО
	ХозрасчетныйОбороты.Субконто2,
	ЕСТЬNULL(ХозрасчетныйОбороты.Субконто3, ЗНАЧЕНИЕ(Справочник.РегистрацииВНалоговомОргане.ПустаяСсылка)),
	ХозрасчетныйОбороты.Организация

ИНДЕКСИРОВАТЬ ПО
	Организация,
	РегистрацияВНалоговомОргане
;

////////////////////////////////////////////////////////////////////////////////
ВЫБРАТЬ
	НалогПоПериодам.РегистрацияВНалоговомОргане КАК РегистрацияВНалоговомОргане,
	ВЫБОР
		КОГДА НалогПоПериодам.Бюджет = ЗНАЧЕНИЕ(Перечисление.УровниБюджетов.ФедеральныйБюджет)
			ТОГДА 1
		ИНАЧЕ РасчетДолейБазыНалогаНаПрибыль.ДоляНалоговойБазы
	КОНЕЦ КАК ДоляНалоговойБазы,
	ВЫБОР
		КОГДА НалогПоПериодам.Бюджет = ЗНАЧЕНИЕ(Перечисление.УровниБюджетов.ФедеральныйБюджет)
			ТОГДА &СтавкаФедеральныйБюджет
		КОГДА НалогПоПериодам.Бюджет <> ЗНАЧЕНИЕ(Перечисление.УровниБюджетов.РегиональныйБюджет)
			ТОГДА 0
		ИНАЧЕ ЕСТЬNULL(РегиональныеСтавки.СтавкаСубъектРФ, &СтавкаРегиональныйБюджет)
	КОНЕЦ КАК СтавкаСубъектРФ,
	НалогПоПериодам.СуммаНалогГод КАК СуммаНалогГод,
	НалогПоПериодам.СуммаНалогМесяц КАК СуммаНалогМесяц,
	НалогПоПериодам.СуммаНалогГод - НалогПоПериодам.СуммаНалогМесяц КАК СуммаНалогОстальныеМесяцы,
	НалогПоПериодам.Бюджет КАК Бюджет,
	НалогПоПериодам.Организация КАК Организация,
	НалогПоПериодам.Организация.ГоловнаяОрганизация КАК ОрганизацияГоловнаяОрганизация
ИЗ
	НалогПоПериодам КАК НалогПоПериодам
		ЛЕВОЕ СОЕДИНЕНИЕ РегистрСведений.РасчетДолейБазыНалогаНаПрибыль КАК РасчетДолейБазыНалогаНаПрибыль
		ПО НалогПоПериодам.Организация = РасчетДолейБазыНалогаНаПрибыль.Организация
			И НалогПоПериодам.РегистрацияВНалоговомОргане = РасчетДолейБазыНалогаНаПрибыль.РегистрацияВНалоговомОргане
			И (РасчетДолейБазыНалогаНаПрибыль.ПериодРасчета МЕЖДУ &НачалоМесяца И &КонецПериода)
		ЛЕВОЕ СОЕДИНЕНИЕ РегистрСведений.СтавкиНалогаНаПрибыльВБюджетСубъектовРФ.СрезПоследних(&КонецПериода, Организация В (&СписокОрганизаций)) КАК РегиональныеСтавки
		ПО НалогПоПериодам.Организация = РегиональныеСтавки.Организация
			И НалогПоПериодам.РегистрацияВНалоговомОргане = РегиональныеСтавки.РегистрацияВНалоговомОргане

**Comment by evgenylavelin** [comment]
Исправлено в версии 3.1.4-b25
