### ISSUE TITLE
Переменная не определена (ЭтотОбъект) в режиме совместимости 8.2.16

### ISSUE THREAD

**Issue by qasef** [evgenylavelin/consquery#32]
Ошибка инициализации модуля: ВнешняяОбработка.КонсольЗапросов.Форма.ФормаУпр.Форма
по причине:
{ВнешняяОбработка.КонсольЗапросов.Форма.ФормаУпр.Форма(580,79)}: Переменная не определена (ЭтотОбъект)
		ПоказатьВводСтроки(Новый ОписаниеОповещения("ПоказатьВводСтрокиЗавершение", <<?>>ЭтотОбъект), гСтроковоеПредставлениеТипа(ТипОбработка, СеансовыеДанные, ТипЗнч(СодержимоеЯчейки)), "Тип значения", ,Истина);

1С:Предприятие 8.3 (8.3.10.2580)
режим совместимости Версия 8.2.16
управляемые формы

**Comment by evgenylavelin** [comment]
Исправлено в 3.1.4-b26
